name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test25
      id: test25
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install pytest
    - name: test26
      id: test26
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 23
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST25_RESULTS: "${{steps.test25.outputs.result}}"
        TEST26_RESULTS: "${{steps.test26.outputs.result}}"
      with:
        runners: test25,test26
